// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4ocsKMKFx07sELBsUmsystmHR83KfErk',
    appId: '1:457434538884:web:ed6d564225c84b754533d1',
    messagingSenderId: '457434538884',
    projectId: 'flutterappstesting',
    authDomain: 'flutterappstesting.firebaseapp.com',
    storageBucket: 'flutterappstesting.appspot.com',
    measurementId: 'G-8M6BQ1KTJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9h4G3lqEMKP6-kizBvDQkA1gLLfIFt_o',
    appId: '1:457434538884:android:cc2d33bc7f4d698a4533d1',
    messagingSenderId: '457434538884',
    projectId: 'flutterappstesting',
    storageBucket: 'flutterappstesting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWWgAo4CywDFyM0CopY6KUcy68F-bI3EU',
    appId: '1:457434538884:ios:7f97bf79a8fbbdbf4533d1',
    messagingSenderId: '457434538884',
    projectId: 'flutterappstesting',
    storageBucket: 'flutterappstesting.appspot.com',
    iosClientId: '457434538884-q5avasmolvve6jh5u14hb1md7lcmfquf.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWWgAo4CywDFyM0CopY6KUcy68F-bI3EU',
    appId: '1:457434538884:ios:7f97bf79a8fbbdbf4533d1',
    messagingSenderId: '457434538884',
    projectId: 'flutterappstesting',
    storageBucket: 'flutterappstesting.appspot.com',
    iosClientId: '457434538884-q5avasmolvve6jh5u14hb1md7lcmfquf.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );
}
